# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = ""
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = ['DATABASE_URL', 'SESSION_SECRET', 'REDWOOD_ENV_FILESTACK_API_KEY', 'EMAIL_JS_SERVICE_KEY', 'EMAIL_JS_TEMPLATE_KEY', 'EMAIL_JS_PUBLIC_KEY', 'REDWOOD_RECAPTCHA_SITE_KEY', 'REDWOOD_RECAPTCHA_SECRET_KEY'] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  port = 8912
[browser]
  open = true
