-- AlterTable
ALTER TABLE "Project" ADD COLUMN "body2" TEXT;
ALTER TABLE "Project" ADD COLUMN "body3" TEXT;
ALTER TABLE "Project" ADD COLUMN "url2" TEXT;
ALTER TABLE "Project" ADD COLUMN "url3" TEXT;
ALTER TABLE "Project" ADD COLUMN "url4" TEXT;
ALTER TABLE "Project" ADD COLUMN "url5" TEXT;
ALTER TABLE "Project" ADD COLUMN "url6" TEXT;
ALTER TABLE "Project" ADD COLUMN "url7" TEXT;
ALTER TABLE "Project" ADD COLUMN "url8" TEXT;
